const $=id=>document.getElementById(id);const state={bridge:null,voice:null,muted:false};
const views=[...document.querySelectorAll('.view')];document.querySelectorAll('#clientNav button').forEach(b=>b.addEventListener('click',()=>showView(b.dataset.view)));document.querySelectorAll('[data-open]').forEach(b=>b.addEventListener('click',()=>showView(b.dataset.open)));
function showView(name){views.forEach(v=>v.classList.toggle('active',v.id===`view-${name}`));document.querySelectorAll('#clientNav button').forEach(b=>b.classList.toggle('active',b.dataset.view===name));if(name==='performance')refreshPerformance()}
function setPill(text,on){const p=$('connectionPill');p.textContent=text;p.className=`pill ${on?'online':'offline'}`}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function capabilities(){const caps=[['WebRTC voice',!!window.RTCPeerConnection],['File import',!!window.FileReader],['Background sync','serviceWorker'in navigator],['Notifications','Notification'in window],['Secure context',window.isSecureContext],['Local storage',!!window.localStorage]];$('capabilities').innerHTML=caps.map(([n,v])=>`<div class="capability"><span>${esc(n)}</span><strong>${v?'Supported':'Unavailable'}</strong></div>`).join('')}
$('refreshCapabilities').addEventListener('click',capabilities);capabilities();
async function connectBridge(){const url=$('bridgeUrl').value.trim().replace(/\/$/,'');if(!url){$('serverStatus').textContent='Enter a bridge URL first.';return}$('serverStatus').textContent='Connecting…';try{const h={};if($('bridgeKey').value.trim())h.Authorization=`Bearer ${$('bridgeKey').value.trim()}`;const r=await fetch(`${url}/api/status`,{headers:h,cache:'no-store'});if(!r.ok)throw Error(`HTTP ${r.status}`);const d=await r.json();state.bridge={url,headers:h};setPill('Server connected',true);$('serverStatus').textContent='Connected.';$('overviewConnection').textContent=d.server?.name||$('serverName').value||'Connected';updatePlayers(d.players||[])}catch(e){state.bridge=null;setPill('Offline',false);$('serverStatus').textContent=`Connection failed: ${e.message}`}}
function updatePlayers(players){$('overviewPlayers').textContent=players.length;$('playerSummary').textContent=`${players.length} player${players.length===1?'':'s'}`;$('playerList').className='list';$('playerList').innerHTML=players.length?players.map(p=>`<div><b>${esc(p.name||'Unknown')}</b><br><small>${esc(p.platform||'Unknown')} · ${esc(p.device||'Unknown')} · ${esc(p.language||'—')}</small></div>`).join(''):'<div>No players online.</div>'}
$('connectBridge').addEventListener('click',connectBridge);$('disconnectBridge').addEventListener('click',()=>{state.bridge=null;setPill('Offline',false);$('serverStatus').textContent='Disconnected.';$('overviewConnection').textContent='Not connected';updatePlayers([])});
async function joinVoice(){if(!window.RTCPeerConnection){$('voiceState').textContent='WebRTC is unavailable on this browser.';return}try{const stream=await navigator.mediaDevices.getUserMedia({audio:true});state.voice={stream};state.muted=false;$('voiceState').textContent='Microphone ready — signaling server not configured';$('voiceUsers').textContent='1 / 10';$('overviewVoice').textContent='Joined';$('muteVoice').textContent='Mute microphone'}catch(e){$('voiceState').textContent=`Microphone permission unavailable: ${e.message}`}}
$('joinVoice').addEventListener('click',joinVoice);$('leaveVoice').addEventListener('click',()=>{state.voice?.stream?.getTracks().forEach(t=>t.stop());state.voice=null;$('voiceState').textContent='Not connected';$('voiceUsers').textContent='0 / 10';$('overviewVoice').textContent='Not joined'});$('muteVoice').addEventListener('click',()=>{if(!state.voice)return;state.muted=!state.muted;state.voice.stream.getAudioTracks().forEach(t=>t.enabled=!state.muted);$('muteVoice').textContent=state.muted?'Unmute microphone':'Mute microphone'});
$('chatForm').addEventListener('submit',e=>{e.preventDefault();const i=$('chatInput');const text=i.value.trim();if(!text)return;const m=document.createElement('div');m.innerHTML=`<b>You</b><br>${esc(text)}`;m.style.cssText='padding:10px;border:1px solid var(--line);border-radius:10px;background:var(--panel2)';$('chatMessages').appendChild(m);i.value='';m.scrollIntoView({behavior:'smooth'})});
$('inspectPacks').addEventListener('click',()=>{const files=[...$('packInput').files];$('packList').className='list';$('packList').innerHTML=files.length?files.map(f=>`<div><b>${esc(f.name)}</b><br><small>${Math.round(f.size/1024)} KB · ${esc(f.type||'Minecraft file')}</small></div>`).join(''):'<div>No files selected.</div>'});
function refreshPerformance(){const c=navigator.connection||navigator.mozConnection||navigator.webkitConnection;$('netType').textContent=c?.effectiveType||'Unavailable';$('memoryInfo').textContent=performance.memory?`${Math.round(performance.memory.usedJSHeapSize/1048576)} MB used`:'Unavailable';$('cpuInfo').textContent=navigator.hardwareConcurrency||'Unavailable';$('displayInfo').textContent=`${screen.width} × ${screen.height}`}
$('pingTest').addEventListener('click',async()=>{if(!state.bridge){$('pingResult').textContent='Connect a bridge first.';return}const t=performance.now();try{const r=await fetch(`${state.bridge.url}/api/health`,{headers:state.bridge.headers,cache:'no-store'});if(!r.ok)throw Error(r.status);$('pingResult').textContent=`API latency: ${Math.round(performance.now()-t)} ms`}catch(e){$('pingResult').textContent=`API test failed: ${e.message}`}});refreshPerformance();
$('resetClient').addEventListener('click',()=>{if(confirm('Reset local PaperLive client settings?')){localStorage.clear();location.reload()}});
if('serviceWorker'in navigator&&location.protocol!=='file:')navigator.serviceWorker.register('sw.js').catch(()=>{});