const $=id=>document.getElementById(id);const state={bridge:null,voice:null,muted:false};
const views=[...document.querySelectorAll('.view')];document.querySelectorAll('#clientNav button').forEach(b=>b.addEventListener('click',()=>showView(b.dataset.view)));document.querySelectorAll('[data-open]').forEach(b=>b.addEventListener('click',()=>showView(b.dataset.open)));
function showView(name){views.forEach(v=>v.classList.toggle('active',v.id===`view-${name}`));document.querySelectorAll('#clientNav button').forEach(b=>b.classList.toggle('active',b.dataset.view===name));if(name==='performance')refreshPerformance()}
function setPill(text,on){const p=$('connectionPill');p.textContent=text;p.className=`pill ${on?'online':'offline'}`}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function capabilities(){const caps=[['WebRTC voice',!!window.RTCPeerConnection],['File import',!!window.FileReader],['Background sync','serviceWorker'in navigator],['Notifications','Notification'in window],['Secure context',window.isSecureContext],['Local storage',!!window.localStorage],['WebSocket','WebSocket'in window]];$('capabilities').innerHTML=caps.map(([n,v])=>`<div class="capability"><span>${esc(n)}</span><strong>${v?'Supported':'Unavailable'}</strong></div>`).join('')}
$('refreshCapabilities').addEventListener('click',capabilities);capabilities();
function bridgeHeaders(){const key=$('bridgeKey').value.trim();return key?{Authorization:`Bearer ${key}`}:{}}
async function connectBridge(){const url=$('bridgeUrl').value.trim().replace(/\/$/,'');if(!url){$('serverStatus').textContent='Enter a bridge URL first.';return}$('serverStatus').textContent='Connecting…';try{const h=bridgeHeaders();const r=await fetch(`${url}/api/status`,{headers:h,cache:'no-store'});if(!r.ok)throw Error(`HTTP ${r.status}`);const d=await r.json();state.bridge={url,headers:h,key:$('bridgeKey').value.trim()};localStorage.setItem('paperlive_bridge_url',url);setPill('Server connected',true);$('serverStatus').textContent='Connected.';$('overviewConnection').textContent=d.server?.name||$('serverName').value||'Connected';updatePlayers(d.players||[])}catch(e){state.bridge=null;setPill('Offline',false);$('serverStatus').textContent=`Connection failed: ${e.message}`}}
function updatePlayers(players){$('overviewPlayers').textContent=players.length;$('playerSummary').textContent=`${players.length} player${players.length===1?'':'s'}`;$('playerList').className='list';$('playerList').innerHTML=players.length?players.map(p=>`<div><b>${esc(p.name||'Unknown')}</b><br><small>${esc(p.platform||'Unknown')} · ${esc(p.device||'Unknown')} · ${esc(p.language||'—')}</small></div>`).join(''):'<div>No players online.</div>'}
$('connectBridge').addEventListener('click',connectBridge);$('disconnectBridge').addEventListener('click',()=>{state.bridge=null;localStorage.removeItem('paperlive_bridge_url');setPill('Offline',false);$('serverStatus').textContent='Disconnected.';$('overviewConnection').textContent='Not connected';updatePlayers([])});
function wsUrl(base){const u=new URL(base);u.protocol=u.protocol==='https:'?'wss:':'ws:';u.pathname='/ws';u.search='';return u.toString()}
function sendSignal(to,data){if(state.voice?.ws?.readyState===1)state.voice.ws.send(JSON.stringify({type:'signal',to,data}))}
async function makePeer(remoteId,offer){if(state.voice.peers.has(remoteId))return state.voice.peers.get(remoteId);const pc=new RTCPeerConnection({iceServers:[{urls:'stun:stun.l.google.com:19302'}]});state.voice.peers.set(remoteId,pc);state.voice.stream.getTracks().forEach(t=>pc.addTrack(t,state.voice.stream));pc.onicecandidate=e=>{if(e.candidate)sendSignal(remoteId,{candidate:e.candidate})};pc.ontrack=e=>{let a=document.querySelector(`audio[data-peer="${remoteId}"]`);if(!a){a=document.createElement('audio');a.autoplay=true;a.dataset.peer=remoteId;a.setAttribute('aria-label','Remote voice');document.body.appendChild(a)}a.srcObject=e.streams[0]};pc.onconnectionstatechange=()=>{if(['failed','closed','disconnected'].includes(pc.connectionState)){pc.close();state.voice.peers.delete(remoteId)}};if(offer){const desc=await pc.createOffer();await pc.setLocalDescription(desc);sendSignal(remoteId,{description:pc.localDescription})}return pc}
async function handleSignal(m){const pc=await makePeer(m.from,false);if(m.data?.description){await pc.setRemoteDescription(m.data.description);if(m.data.description.type==='offer'){const answer=await pc.createAnswer();await pc.setLocalDescription(answer);sendSignal(m.from,{description:pc.localDescription})}}else if(m.data?.candidate){try{await pc.addIceCandidate(m.data.candidate)}catch{}}}
async function joinVoice(){if(!window.RTCPeerConnection||!window.WebSocket){$('voiceState').textContent='This browser cannot run PaperLive voice.';return}try{const stream=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true,autoGainControl:true}});const room=($('voiceRoom').value.trim()||'lobby').slice(0,40);const signalBase=state.bridge?.url||$('bridgeUrl').value.trim();if(!signalBase)throw Error('Connect to a PaperLive API first');const ws=new WebSocket(wsUrl(signalBase));state.voice={stream,ws,room,peers:new Map(),key:state.bridge?.key||$('bridgeKey').value.trim()};ws.onopen=()=>{ws.send(JSON.stringify({type:'auth',key:state.voice.key}));$('voiceState').textContent='Authenticating voice connection…'};ws.onmessage=async e=>{let m;try{m=JSON.parse(e.data)}catch{return}if(m.type==='authenticated'){ws.send(JSON.stringify({type:'join',room}));$('voiceState').textContent='Joining voice room…'}else if(m.type==='joined'){$('voiceState').textContent=`Joined ${m.room}`;$('voiceUsers').textContent=`${m.users} / 10`;$('overviewVoice').textContent='Joined';for(const id of m.existing||[])await makePeer(id,true)}else if(m.type==='user-joined'){$('voiceUsers').textContent=`${m.users} / 10`}else if(m.type==='user-left'){const pc=state.voice?.peers.get(m.userId);pc?.close();state.voice?.peers.delete(m.userId);document.querySelector(`audio[data-peer="${m.userId}"]`)?.remove();$('voiceUsers').textContent=`${m.users} / 10`}else if(m.type==='signal'){await handleSignal(m)}else if(m.type==='chat'){appendChat(m.from,m.text)}else if(m.type==='error'){$('voiceState').textContent=m.message||'Voice connection error.'}};ws.onclose=()=>{if(state.voice?.ws===ws)$('voiceState').textContent='Voice signaling disconnected'};state.muted=false;$('muteVoice').textContent='Mute microphone'}catch(e){$('voiceState').textContent=`Voice unavailable: ${e.message}`}}
function appendChat(from,text){const m=document.createElement('div');m.innerHTML=`<b>${esc(from||'User')}</b><br>${esc(text)}`;m.style.cssText='padding:10px;border:1px solid var(--line);border-radius:10px;background:var(--panel2)';$('chatMessages').appendChild(m);m.scrollIntoView({behavior:'smooth'})}
$('joinVoice').addEventListener('click',joinVoice);$('leaveVoice').addEventListener('click',()=>{state.voice?.ws?.close();state.voice?.peers?.forEach(pc=>pc.close());state.voice?.stream?.getTracks().forEach(t=>t.stop());document.querySelectorAll('audio[data-peer]').forEach(a=>a.remove());state.voice=null;$('voiceState').textContent='Not connected';$('voiceUsers').textContent='0 / 10';$('overviewVoice').textContent='Not joined'});$('muteVoice').addEventListener('click',()=>{if(!state.voice)return;state.muted=!state.muted;state.voice.stream.getAudioTracks().forEach(t=>t.enabled=!state.muted);$('muteVoice').textContent=state.muted?'Unmute microphone':'Mute microphone'});
$('chatForm').addEventListener('submit',e=>{e.preventDefault();const i=$('chatInput');const text=i.value.trim();if(!text)return;appendChat('You',text);if(state.voice?.ws?.readyState===1)state.voice.ws.send(JSON.stringify({type:'chat',text}));i.value=''});
$('inspectPacks').addEventListener('click',()=>{const files=[...$('packInput').files];$('packList').className='list';$('packList').innerHTML=files.length?files.map(f=>`<div><b>${esc(f.name)}</b><br><small>${Math.round(f.size/1024)} KB · ${esc(f.type||'Minecraft file')}</small></div>`).join(''):'<div>No files selected.</div>'});
function refreshPerformance(){const c=navigator.connection||navigator.mozConnection||navigator.webkitConnection;$('netType').textContent=c?.effectiveType||'Unavailable';$('memoryInfo').textContent=performance.memory?`${Math.round(performance.memory.usedJSHeapSize/1048576)} MB used`:'Unavailable';$('cpuInfo').textContent=navigator.hardwareConcurrency||'Unavailable';$('displayInfo').textContent=`${screen.width} × ${screen.height}`}
$('pingTest').addEventListener('click',async()=>{if(!state.bridge){$('pingResult').textContent='Connect a bridge first.';return}const t=performance.now();try{const r=await fetch(`${state.bridge.url}/api/health`,{headers:state.bridge.headers,cache:'no-store'});if(!r.ok)throw Error(r.status);$('pingResult').textContent=`API latency: ${Math.round(performance.now()-t)} ms`}catch(e){$('pingResult').textContent=`API test failed: ${e.message}`}});refreshPerformance();
const savedBridge=localStorage.getItem('paperlive_bridge_url');if(savedBridge)$('bridgeUrl').value=savedBridge;
$('resetClient').addEventListener('click',()=>{if(confirm('Reset local PaperLive client settings?')){localStorage.clear();location.reload()}});
if('serviceWorker'in navigator&&location.protocol!=='file:')navigator.serviceWorker.register('sw.js').catch(()=>{});