document.addEventListener('DOMContentLoaded',()=>{
  const input=document.getElementById('fileUploadInput');
  const buttons=[document.getElementById('uploadButton'),document.getElementById('uploadButtonSecondary')].filter(Boolean);
  const dropZone=document.getElementById('dropZone');
  const status=document.getElementById('uploadStatus'); const list=document.getElementById('uploadedFiles');
  if(!input||(!buttons.length&&!dropZone)||!status||!list||!window.FireflyFileStorage)return;
  const formatSize=bytes=>bytes<1024?`${bytes} B`:bytes<1048576?`${(bytes/1024).toFixed(1)} KB`:`${(bytes/1048576).toFixed(1)} MB`;
  const render=async()=>{const files=await FireflyFileStorage.getAll();list.innerHTML='';if(!files.length){list.innerHTML='<p class="empty">No files saved in this browser.</p>';return;}files.sort((a,b)=>new Date(b.uploadedAt)-new Date(a.uploadedAt)).forEach(item=>{const row=document.createElement('div');row.className='saved-server';const info=document.createElement('div');info.className='saved-server-info';const title=document.createElement('strong');title.textContent=item.name;const details=document.createElement('span');details.textContent=`${formatSize(item.size)} • ${item.type||'Unknown type'}`;info.append(title,details);const actions=document.createElement('div');actions.className='saved-server-actions';const open=document.createElement('button');open.className='button secondary';open.type='button';open.textContent='Open';open.addEventListener('click',()=>{const url=URL.createObjectURL(item.blob);window.open(url,'_blank','noopener,noreferrer');setTimeout(()=>URL.revokeObjectURL(url),60000);});const remove=document.createElement('button');remove.className='button danger-button';remove.type='button';remove.textContent='Delete';remove.addEventListener('click',async()=>{await FireflyFileStorage.remove(item.id);await render();});actions.append(open,remove);row.append(info,actions);list.appendChild(row);});};
  const saveFiles=async(fileList)=>{const files=Array.from(fileList||[]);if(!files.length){status.textContent='No files were selected. Choose files from your device to upload them.';status.style.color='var(--muted)';return;}status.textContent=`Saving ${files.length} file${files.length===1?'':'s'}…`;status.style.color='var(--muted)';buttons.forEach(b=>b.disabled=true);if(dropZone)dropZone.classList.add('is-uploading');try{for(const file of files)await FireflyFileStorage.put(file);status.textContent=`Saved ${files.length} file${files.length===1?'':'s'} in this browser.`;await render();}catch(error){status.textContent=`Upload failed: ${error instanceof Error?error.message:String(error)}`;status.style.color='var(--danger)';}finally{buttons.forEach(b=>b.disabled=false);if(dropZone)dropZone.classList.remove('is-uploading');input.value='';}};
  const openFilePicker=()=>{status.textContent='Choose the files you want to upload from your device.';status.style.color='var(--muted)';input.click();};
  buttons.forEach(button=>button.addEventListener('click',openFilePicker));
  input.addEventListener('change',()=>saveFiles(input.files));
  if(dropZone){
    ['dragenter','dragover'].forEach(eventName=>dropZone.addEventListener(eventName,event=>{event.preventDefault();event.stopPropagation();dropZone.classList.add('is-dragging');}));
    ['dragleave','dragend','drop'].forEach(eventName=>dropZone.addEventListener(eventName,event=>{event.preventDefault();event.stopPropagation();if(eventName!=='drop')dropZone.classList.remove('is-dragging');}));
    dropZone.addEventListener('drop',event=>{dropZone.classList.remove('is-dragging');saveFiles(event.dataTransfer?.files);});
    dropZone.addEventListener('keydown',event=>{if((event.key==='Enter'||event.key===' ')&&event.target===dropZone){event.preventDefault();openFilePicker();}});
  }
  document.getElementById('clearUploadedFilesButton')?.addEventListener('click',async()=>{try{await FireflyFileStorage.clear();status.textContent='Private browser files cleared.';status.style.color='var(--muted)';await render();}catch(error){status.textContent=`Could not clear files: ${error instanceof Error?error.message:String(error)}`;status.style.color='var(--danger)';}});
  render().catch(()=>{status.textContent='Private file storage is unavailable in this browser.';status.style.color='var(--danger)';});
});
