(() => {
  const $=id=>document.getElementById(id);
  const languages=['JavaScript','TypeScript','Java','Python','C','C++','C#','Go','Rust','Kotlin','Swift','PHP','Ruby','Lua','Dart','R','Scala','Perl','Haskell','Elixir','Erlang','D','Zig','Objective-C','SQL','HTML','CSS','SCSS','Sass','XML','JSON','YAML','Markdown','Bash','PowerShell','Shell','Assembly','Fortran','COBOL','Groovy','MATLAB','Julia','Visual Basic','Solidity','GraphQL','Dockerfile','TOML','Vue','Svelte'];
  const extMap={JavaScript:'js',TypeScript:'ts',Java:'java',Python:'py','C':'c','C++':'cpp','C#':'cs',Go:'go',Rust:'rs',Kotlin:'kt',Swift:'swift',PHP:'php',Ruby:'rb',Lua:'lua',Dart:'dart',R:'r',Scala:'scala',Perl:'pl',Haskell:'hs',Elixir:'ex',Erlang:'erl',D:'d',Zig:'zig','Objective-C':'m',SQL:'sql',HTML:'html',CSS:'css',SCSS:'scss',Sass:'sass',XML:'xml',JSON:'json',YAML:'yml',Markdown:'md',Bash:'sh',PowerShell:'ps1',Shell:'sh',Assembly:'asm',Fortran:'f90',COBOL:'cob',Groovy:'groovy',MATLAB:'m',Julia:'jl','Visual Basic':'vb',Solidity:'sol',GraphQL:'graphql',Dockerfile:'dockerfile',TOML:'toml',Vue:'vue',Svelte:'svelte'};
  const launcher=$('launcher'), app=$('app'), bar=$('progressBar'), percent=$('percent'), size=$('size');
  function runTimedLaunch(duration, onProgress, onDone){const start=performance.now();function frame(now){const ratio=Math.min(1,(now-start)/duration);const p=Math.max(1,Math.floor(ratio*99)+1);onProgress(p,ratio);if(ratio<1)requestAnimationFrame(frame);else onDone()}requestAnimationFrame(frame)}
  runTimedLaunch(45000,(p,r)=>{bar.style.width=p+'%';percent.textContent=p+'%';size.textContent=(6.3*r).toFixed(1)+'/6.3mb'},()=>{bar.style.width='100%';percent.textContent='100%';size.textContent='6.3/6.3mb';setTimeout(()=>{launcher.classList.add('hidden');launcher.setAttribute('aria-hidden','true');app.classList.remove('hidden');log('FL Code Beta B1.5.0 ready.');renderTree()},250)});

  const lang=$('languageSelect'); languages.forEach(x=>{const o=document.createElement('option');o.value=x;o.textContent=x;lang.appendChild(o)});
  let selectedId=null, contextId=null, activeFile=null;
  function items(){return FLBackend.all()}
  function log(msg){const c=$('console');if(c){c.textContent+=(c.textContent?'\n':'')+'['+new Date().toLocaleTimeString()+'] '+msg;c.scrollTop=c.scrollHeight}}
  function toast(msg){const t=$('toast');t.textContent=msg;t.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>t.classList.remove('show'),1800)}
  function view(name){document.querySelectorAll('.view').forEach(v=>v.classList.remove('active-view'));$('view-'+name).classList.add('active-view');document.querySelectorAll('.category').forEach(b=>b.classList.toggle('active',b.dataset.view===name))}
  document.querySelectorAll('[data-view]').forEach(b=>b.addEventListener('click',()=>view(b.dataset.view)));
  function icon(item){return item.type==='folder'?'📁':item.type==='network'?'🌐':item.type==='package'?'📦':'📄'}
  function renderTree(){const root=$('explorer');root.innerHTML='';const data=items();const children=(parent,depth)=>data.filter(x=>x.parent===parent&&!x.hidden).forEach(item=>{const row=document.createElement('div');row.className='tree-item'+(item.id===selectedId?' selected':'');row.dataset.id=item.id;row.style.paddingLeft=(10+depth*22)+'px';const ico=document.createElement('span');ico.className='tree-icon';ico.textContent=icon(item);const name=document.createElement('span');name.className='tree-name';name.textContent=item.name;row.append(ico,name);row.addEventListener('click',e=>{e.stopPropagation();select(item.id);if(item.type==='file')openFile(item.id)});row.addEventListener('contextmenu',e=>{e.preventDefault();e.stopPropagation();contextId=item.id;showMenu(e.clientX,e.clientY)});root.appendChild(row);if(item.type==='folder'||item.type==='network'||item.type==='package')children(item.id,depth+1)});children(null,0);if(!root.children.length)root.innerHTML='<div class="muted">No visible files.</div>'}
  function select(id){selectedId=id;renderTree();const item=FLBackend.get(id);if(item)toast('Selected '+item.name)}
  function openFile(id){const item=FLBackend.get(id);if(!item||item.type!=='file')return;activeFile=id;$('editorTitle').textContent='Editor • '+item.name;lang.value=item.language||languageFromName(item.name);$('editor').value=item.content||'';view('editor')}
  function languageFromName(n){const ext=(n.split('.').pop()||'').toLowerCase();const found=Object.entries(extMap).find(([,e])=>e===ext);return found?found[0]:'Plain Text'}
  $('editor').addEventListener('input',()=>{if(activeFile)FLBackend.update(activeFile,{content:$('editor').value,language:lang.value})});lang.addEventListener('change',()=>{if(activeFile)FLBackend.update(activeFile,{language:lang.value})});
  function newItem(type){const name=prompt('Name for the new '+type+':');if(!name)return;const parent=selectedId&&FLBackend.get(selectedId)?.type==='folder'?selectedId:'root';const item={id:crypto.randomUUID(),name,type,parent,hidden:false};if(type==='file'){item.language=languageFromName(name);item.content=''}FLBackend.create(item);renderTree();select(item.id);log('Created '+name)}
  $('newFile').onclick=()=>newItem('file');$('newFolder').onclick=()=>newItem('folder');$('newNetwork').onclick=()=>newItem('network');$('newPackage').onclick=()=>newItem('package');
  function showMenu(x,y){const m=$('contextMenu');m.hidden=false;m.style.left=Math.min(x,innerWidth-195)+'px';m.style.top=Math.min(y,innerHeight-260)+'px'}
  addEventListener('click',()=>{$('contextMenu').hidden=true});
  $('contextMenu').addEventListener('click',e=>{const action=e.target.dataset.action;if(!action||!contextId)return;$('contextMenu').hidden=true;const item=FLBackend.get(contextId);if(!item)return;switch(action){case 'select':select(item.id);break;case 'delete':if(confirm('Delete '+item.name+'?')){FLBackend.remove(item.id);if(activeFile===item.id){activeFile=null;$('editor').value=''}renderTree();log('Deleted '+item.name)}break;case 'move':{const dest=prompt('Move to folder ID (or leave blank for root):','root');if(dest!==null){const d=dest||'root';const folder=FLBackend.get(d);if(d==='root'||folder?.type==='folder'){FLBackend.update(item.id,{parent:d});renderTree();log('Moved '+item.name)}else toast('That is not a folder.')}}break;case 'download':downloadItem(item);break;case 'zip':zipItem(item);break;case 'hide':FLBackend.update(item.id,{hidden:!item.hidden});renderTree();log((item.hidden?'Unhid ':'Hid ')+item.name);break}});
  function downloadItem(item){if(item.type!=='file'){toast('Folders and groups can be zipped instead.');return}const blob=new Blob([item.content||''],{type:'text/plain;charset=utf-8'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=item.name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500);log('Downloaded '+item.name)}
  function crc32(bytes){let c=0xffffffff;for(const b of bytes){c^=b;for(let k=0;k<8;k++)c=(c>>>1)^((c&1)?0xedb88320:0)}return(c^0xffffffff)>>>0}
  function u16(n){return new Uint8Array([n&255,n>>>8&255])}function u32(n){return new Uint8Array([n&255,n>>>8&255,n>>>16&255,n>>>24&255])}
  function zipItem(item){const all=items().filter(x=>x.type==='file'&&(x.id===item.id||x.parent===item.id));if(!all.length){toast('Nothing to zip here.');return}let chunks=[],offset=0,central=[];for(const f of all){const name=new TextEncoder().encode(f.name),data=new TextEncoder().encode(f.content||'');const local=new Uint8Array(30+name.length+data.length);local.set(u32(0x04034b50),0);local.set(u16(20),4);local.set(u16(0),6);local.set(u16(0),8);local.set(u16(0),10);local.set(u16(0),12);local.set(u32(crc32(data)),14);local.set(u32(data.length),18);local.set(u32(data.length),22);local.set(u16(name.length),26);local.set(u16(0),28);local.set(name,30);local.set(data,30+name.length);chunks.push(local);const cen=new Uint8Array(46+name.length);cen.set(u32(0x02014b50),0);cen.set(u16(20),4);cen.set(u16(20),6);cen.set(u16(0),8);cen.set(u16(0),10);cen.set(u16(0),12);cen.set(u16(0),14);cen.set(u32(crc32(data)),16);cen.set(u32(data.length),20);cen.set(u32(data.length),24);cen.set(u16(name.length),28);cen.set(u16(0),30);cen.set(u16(0),32);cen.set(u16(0),34);cen.set(u16(0),36);cen.set(u32(0),38);cen.set(u32(offset),42);cen.set(name,46);central.push(cen);offset+=local.length}const centralSize=central.reduce((n,x)=>n+x.length,0),end=new Uint8Array(22);end.set(u32(0x06054b50),0);end.set(u16(0),4);end.set(u16(0),6);end.set(u16(central.length),8);end.set(u16(central.length),10);end.set(u32(centralSize),12);end.set(u32(offset),16);end.set(u16(0),20);const blob=new Blob([...chunks,...central,end],{type:'application/zip'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=item.name+'.zip';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),700);log('Created ZIP for '+item.name)}
  function returnToNormalMode(){const overlay=$('returnLauncher');overlay.classList.remove('hidden');overlay.setAttribute('aria-hidden','false');app.classList.add('hidden');const rb=$('returnProgressBar'),rp=$('returnPercent');runTimedLaunch(20000,(p)=>{rb.style.width=p+'%';rp.textContent=p+'%'},()=>{rb.style.width='100%';rp.textContent='100%';setTimeout(()=>location.href='../',250)})}
  $('normalModeButton').onclick=returnToNormalMode;
  $('runButton').onclick=()=>{if(activeFile){log('Run requested for '+FLBackend.get(activeFile)?.name);log('Browser beta runner: arbitrary Java/JS/TS execution is intentionally not enabled by this static build.')}else log('Select a source file before running.')};
  $('clearConsole').onclick=()=>$('console').textContent='';$('resetButton').onclick=()=>{if(confirm('Reset the FL Code Beta workspace?')){FLBackend.reset();activeFile=null;selectedId=null;$('editor').value='';renderTree();log('Workspace reset.')}};
})();

